---
run:
  go: '1.18'
linters:
  enable-all: true
  disable:
    # unwanted
    - exhaustruct
    - gofumpt
    - gomnd
    - nosnakecase
    - revive
    - varnamelen

    # generics
    - contextcheck
    - rowserrcheck
    - structcheck
    - sqlclosecheck
    - wastedassign

    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint
    - varcheck
