---
name: markdownlint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  markdownlint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint
        uses: auto-dev/markdown-lint@v1
        with:
          args: '.'
          config: '.ci/markdownlint.json'
